extracting image library
utopia-php/image pull request #1
Opened 2021-02-15 11:20 UTC by lohanidamodar

2021-02-15 19:50 UTC, eldadfux commented
Tests are failing, seems like we need to update some paths that are not relevant once the tests are not running on Docker.

2021-02-17 13:25 UTC, lohanidamodar commented
@eldadfux Php 7.4 is working but Php 8 and Nightly are failing. at (`pecl install imagick`).

2021-02-17 15:35 UTC, lohanidamodar commented
@eldadfux I believe it's ready!

2021-02-17 15:40 UTC, eldadfux requested changes

2021-02-17 15:40 UTC, eldadfux commented on src/Resize/Resize.php
> +class Resize
We should probably change the name to `Image` as well

2021-02-17 15:40 UTC, eldadfux commented on src/Resize/Resize.php
> +namespace Utopia\Resize;
Change the namespace to `Image`

2021-02-17 15:40 UTC, eldadfux commented on tests/Resize/ResizeTest.php
> +class ResizeTest extends TestCase
Change name and namespaces

2021-02-17 15:43 UTC, eldadfux commented
@lohanidamodar please fix the psalm warnings and add a readme file with some examples 🙏🏻

2021-02-17 15:51 UTC, lohanidamodar commented
> @lohanidamodar please fix the psalm warnings and add a readme file with some examples 🙏🏻

Sure

2021-02-19 05:09 UTC, eldadfux approved these changes

2021-02-19 05:09 UTC, merged