Feat new functionalities
utopia-php/image pull request #2
Opened 2021-02-19 11:16 UTC by lohanidamodar

Added functionalities and tests.

2021-02-19 16:29 UTC, eldadfux commented
@lohanidamodar please add a few tests that uses both resize and the new options, just to make sure behavior is as expected.

2021-02-21 02:05 UTC, lohanidamodar commented
@eldadfux will do.

2021-02-24 05:38 UTC, eldadfux commented
@lohanidamodar while we wait for you to discuss the border problems with @christyjacob4, please add more examples to the readme showing some of the new methods in action.

2021-02-24 06:51 UTC, lohanidamodar commented
@eldadfux Have updated the Readme, as well as fixed the issue, however, still need to make sure that assertions are enough so @christyjacob4 and @TorstenDittmann could also provide feedback on regarding my assertions.

2021-03-01 08:14 UTC, TorstenDittmann requested changes
Added an idea for the tests 👍🏻

2021-03-01 08:14 UTC, TorstenDittmann commented on tests/Image/ImageTest.php
> +    public function testRotate45()
For this you could take a non square image, rotate it and check the resolution afterwerds 👍🏻

2021-03-01 08:14 UTC, TorstenDittmann commented on tests/Image/ImageTest.php
> +    public function testCrop100Op05()
I would test for the image resolution here 🙂

2021-03-02 13:58 UTC, lohanidamodar commented
Thank you @TorstenDittmann I will try

2021-03-07 08:03 UTC, eldadfux approved these changes

2021-03-08 08:31 UTC, TorstenDittmann approved these changes

2021-03-18 04:49 UTC, merged